

export const randomMessages = [
    "Ciao, mondo!",
    "Buongiorno!",
    "Come stai?",
    "Ho fame.",
    "Mi piace il gelato.",
    "Sto ascoltando musica.",
    "Ho bisogno di un caffè.",
    "Mi sono perso/a.",
    "Buon compleanno!",
    "Mi manchi.",
    "Ho visto un arcobaleno oggi.",
    "Ho fatto una passeggiata al parco.",
    "Mi sono innamorato/a.",
    "Ho bisogno di una vacanza.",
    "Ho appena risolto un problema di programmazione.",
    "Mi piace leggere libri.",
    "Ho fatto una foto bellissima.",
    "Ho bisogno di un massaggio.",
    "Mi sono divertito/a alla festa ieri sera.",
    "Ho visto un film fantastico.",
    "Ho bisogno di un consiglio.",
    "Mi piace ballare.",
    "Ho trovato un gattino per strada.",
    "Ho scritto una poesia.",
    "Mi piace guardare le stelle.",
    "Ho bisogno di un nuovo paio di scarpe.",
    "Mi sono iscritto/a in palestra.",
    "Ho fatto una playlist su Spotify.",
    "Mi piace cucinare.",
    "Ho visto un concerto live.",
    "Ho bisogno di un abbraccio.",
    "Mi piace viaggiare.",
    "Ho ricevuto un complimento.",
    "Ho bisogno di un nuovo profumo.",
    "Mi piace il sushi.",
    "Ho fatto una passeggiata sulla spiaggia.",
    "Mi piace il sole.",
    "Ho bisogno di un consiglio su quale serie TV guardare.",
    "Mi piace dipingere.",
    "Ho visto una farfalla oggi.",
    "La vita è ciò che accade mentre stai facendo altri piani.",
    "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.",
    "La felicità non è qualcosa di pronto. Viene dalle tue azioni.",
    "La creatività è contagiosa, passala.",
    "Non aspettare. Il momento perfetto non esiste mai.",
    "La gentilezza è gratuita. Spargila ovunque.",
    "La saggezza comincia con l'umiltà.",
    "La vita è breve, sorridi mentre hai ancora i denti.",
    "Non guardare indietro, stai andando nella giusta direzione.",
    "La tua unica limitazione è la tua mente.",
];